include(FetchContent)

FetchContent_Declare(
	GLFW
	GIT_REPOSITORY https://github.com/glfw/glfw.git
	GIT_TAG 3.3.4
	GIT_SHALLOW TRUE
)
FetchContent_GetProperties(GLFW)
if(NOT glfw_POPULATED)
	FetchContent_Populate(GLFW)

	set(GLFW_BUILD_DOCS OFF CACHE INTERNAL "")
	set(GLFW_BUILD_TESTS OFF CACHE INTERNAL "")
	set(GLFW_BUILD_EXAMPLES OFF CACHE INTERNAL "")
	if(FORCE_STATIC_VCRT)
		set(USE_MSVC_RUNTIME_LIBRARY_DLL OFF CACHE INTERNAL "")
	else()
		set(USE_MSVC_RUNTIME_LIBRARY_DLL ON CACHE INTERNAL "")
	endif()
	set(CMAKE_INSTALL_PREFIX ${INSTALL_DIR} CACHE INTERNAL "")
	set(CMAKE_BUILD_TYPE ${CONFIG} CACHE INTERNAL "")
	set(CMAKE_DEBUG_POSTFIX ${MY_DEBUG_POSTFIX} CACHE INTERNAL "")
	set(BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS} CACHE INTERNAL "")

	add_subdirectory(${glfw_SOURCE_DIR} ${glfw_BINARY_DIR})
endif()
