# Sets all the dependencies of the project
option(INSTALLED_GLM "Use installed glm library" ON)
option(INSTALLED_GLEW "Use installed glew library" ON)
option(INSTALLED_GLFW "Use installed glfw library" ON)
option(INSTALLED_SOIL "Use installed soil library" ON)
option(INSTALLED_GTEST "Use installed gtest library" ON)

find_package(Git REQUIRED)

if(FAZE_ENGINE_BUILD_DOC)
	find_package(Doxygen)
endif()

find_package(OpenGL REQUIRED)
add_library(opengl INTERFACE)
target_include_directories(opengl INTERFACE "${OPENGL_INCLUDE_DIR}")
target_link_libraries(opengl INTERFACE "${OPENGL_LIBRARIES}")

find_package(GLM "0.9.8" REQUIRED)
if(GLM_FOUND AND INSTALLED_GLM)
	message("GLM FOUND: Using system library")
else()
	message("GLM NOT FOUND: Downloading and building GLM from source")
	include(ExternalGLM)
endif()

find_package(GLEW "1.13.0" QUIET)
if(GLEW_FOUND AND INSTALLED_GLEW)
	message("GLEW FOUND: Using system library")
else()
	message("GLEW NOT FOUND: Downloading and building GLEW from source")
	include(ExternalGLEW)
endif()

find_package(GLFW "3.2.1" QUIET)
if(GLFW_FOUND AND INSTALLED_GLFW)
	message("GLFW FOUND: Using system library")
else()
	message("GLFW NOT FOUND: Downloading and building GLFW from source")
	include(ExternalGLFW)
endif()

find_package(SOIL QUIET)
if(SOIL_FOUND AND INSTALLED_SOIL)
	message("SOIL FOUND: Using system library")
else()
	message("SOIL NOT FOUND: Downloading and building SOIL from source")
	include(ExternalSOIL)
endif()

find_package(GTEST QUIET)
if(GTEST_FOUND AND INSTALLED_GTEST)
	message("GTEST FOUND: Using system library")
else()
	message("GTEST NOT FOUND: Downloading and building GTEST from source")
	include(ExternalGTest)
endif()
