include(ExternalProject)
ExternalProject_Add(
	glfw
	GIT_REPOSITORY	"https://github.com/glfw/glfw"
	GIT_TAG			"3.2.1"
	SOURCE_DIR		"${EXTERNAL_PATH}/glfw"
	INSTALL_DIR		"${EXTERNAL_INSTALL_LOCATION}"
	UPDATE_COMMAND	""
	PATCH_COMMAND	""
	TEST_COMMAND	""
	CMAKE_ARGS		"-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}"
					"-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>"
)

set(GLFW_FOUND TRUE)
set(GLFW_INCLUDE_DIR "${EXTERNAL_INSTALL_LOCATION}/include")
if (BUILD_SHARED_LIBS)
	set(GLFW_LIBRARY "${EXTERNAL_INSTALL_LOCATION}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}glfw3${CMAKE_SHARED_LIBRARY_SUFFIX}")
else()
	set(GLFW_LIBRARY "${EXTERNAL_INSTALL_LOCATION}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}glfw3${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()

if(UNIX)
	find_package(Threads REQUIRED)
	find_package(
		X11
		REQUIRED
		COMPONENTS X11_Xrandr X11_xf86vmode X11_Xcursor X11_Xinerama X11_Xinput
	)

	list(APPEND GLFW_LIBRARY ${X11_LIBRARIES} ${X11_Xrandr_LIB} ${X11_Xxf86vm_LIB} ${X11_Xcursor_LIB} ${X11_Xinerama_LIB} ${X11_Xinput_LIB} ${CMAKE_THREAD_LIBS_INIT} -ldl)
endif()
