include(ExternalProject)
ExternalProject_Add(
	soil
	GIT_REPOSITORY	"https://github.com/kbranigan/Simple-OpenGL-Image-Library"
	GIT_TAG			"master"
	SOURCE_DIR		"${EXTERNAL_PATH}/soil"
	INSTALL_DIR		"${EXTERNAL_INSTALL_LOCATION}"
	UPDATE_COMMAND	""
	PATCH_COMMAND	""
	TEST_COMMAND	""
	CMAKE_ARGS		"-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}"
					"-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>"
)

set(SOIL_FOUND TRUE)
set(SOIL_INCLUDE_DIR "${EXTERNAL_INSTALL_LOCATION}/include")
if (BUILD_SHARED_LIBS)
	set(SOIL_LIBRARY "${EXTERNAL_INSTALL_LOCATION}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}SOIL${CMAKE_SHARED_LIBRARY_SUFFIX}")
else()
	set(SOIL_LIBRARY "${EXTERNAL_INSTALL_LOCATION}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}SOIL${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()
